// This file is auto-generated by @hey-api/openapi-ts

export type CreateSessionRequest = {
    session_id: string;
    policy_path: string;
    camera_names?: Array<(string)>;
    transport_server_url?: string;
    workspace_id?: (string | null);
    policy_type?: string;
    language_instruction?: (string | null);
};

export type CreateSessionResponse = {
    workspace_id: string;
    camera_room_ids: {
        [key: string]: (string);
    };
    joint_input_room_id: string;
    joint_output_room_id: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type SessionStatusResponse = {
    session_id: string;
    status: string;
    policy_path: string;
    policy_type: string;
    camera_names: Array<(string)>;
    workspace_id: string;
    rooms: {
        [key: string]: unknown;
    };
    stats: {
        [key: string]: unknown;
    };
    inference_stats?: ({
    [key: string]: unknown;
} | null);
    error_message?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type RootGetResponse = (unknown);

export type RootGetError = unknown;

export type HealthCheckHealthGetResponse = (unknown);

export type HealthCheckHealthGetError = unknown;

export type ListSessionsSessionsGetResponse = (Array<SessionStatusResponse>);

export type ListSessionsSessionsGetError = unknown;

export type CreateSessionSessionsPostData = {
    body: CreateSessionRequest;
};

export type CreateSessionSessionsPostResponse = (CreateSessionResponse);

export type CreateSessionSessionsPostError = (HTTPValidationError);

export type StartInferenceSessionsSessionIdStartPostData = {
    path: {
        session_id: string;
    };
};

export type StartInferenceSessionsSessionIdStartPostResponse = (unknown);

export type StartInferenceSessionsSessionIdStartPostError = (HTTPValidationError);

export type StopInferenceSessionsSessionIdStopPostData = {
    path: {
        session_id: string;
    };
};

export type StopInferenceSessionsSessionIdStopPostResponse = (unknown);

export type StopInferenceSessionsSessionIdStopPostError = (HTTPValidationError);

export type RestartInferenceSessionsSessionIdRestartPostData = {
    path: {
        session_id: string;
    };
};

export type RestartInferenceSessionsSessionIdRestartPostResponse = (unknown);

export type RestartInferenceSessionsSessionIdRestartPostError = (HTTPValidationError);

export type DeleteSessionSessionsSessionIdDeleteData = {
    path: {
        session_id: string;
    };
};

export type DeleteSessionSessionsSessionIdDeleteResponse = (unknown);

export type DeleteSessionSessionsSessionIdDeleteError = (HTTPValidationError);